cargo-features = ["edition2024"]

[package]
edition = "2024"
name = "day01"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helpers.workspace = true
solver-interface.workspace = true
